title: root.red
description: Personal security/research writeups, guides, and thoughts
baseurl: "" 
url: "https://root.red"

remote_theme: jekyll/minima  # <-- This line instead of theme: minima

minima:
  skin: dark  # or auto

header_pages:
  - about.md
  - writeups.md

show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme  # <-- Add this
